### ISSUE TITLE
setRawProperty not working

### ISSUE THREAD

**Issue by TacticalTux** [rojo-rbx/remodel#30]
```lua
local test = Instance.new("StringValue")
remodel.setRawProperty(test, "Value", string, test)
```
(or)
```lua
local test = Instance.new("StringValue")
remodel.setRawProperty(test, "Value", "string", test)
```
```
[ERROR] callback error: error converting Lua table to String (expected string or number): stack traceback:
                [C]: in ?
                [C]: in field 'setRawProperty'
                [string "remodel.lua"]:2: in main chunk

        Caused by:
            error converting Lua table to String (expected string or number)
```

Upon attempting to read and write script objects, I encountered an error using setRawProperty, and upon further testing, it seems to be impacting it as a whole above. Failing code is above, with the error below it.

**Comment by LPGhatguy** [comment]
This API usage is not correct. [The signature of `setRawProperty`](https://github.com/rojo-rbx/remodel#remodelsetrawproperty-060) lays out the required types.

[Here is an example](https://github.com/rojo-rbx/remodel/blob/65e2f9b79cc9eda308a355cff48f99070df079eb/test-scripts/raw-property-new.lua) from the Remodel test suite that shows how to use `setRawProperty`. For your example, you should write something like this:

```lua
local test = Instance.new("StringValue")
remodel.setRawProperty(test, "Value", "String", "Hello, world!")
```
