### ISSUE TITLE
rbxlx readPlaceFile Error

### ISSUE THREAD

**Issue by MaxBorsch** [rojo-rbx/remodel#31]
I get an error when I try to read my (new and working) place file with `local game = remodel.readPlaceFile("place.rbxlx")`:
![powershell_Ze8OtKdqTl](https://user-images.githubusercontent.com/2924585/110222948-1f8fbe00-7e8b-11eb-818f-105c51aac9d6.png)

**Comment by Kampfkarren** [comment]
This is likely fixed on master, can you test with that?

**Comment by MaxBorsch** [comment]
@Kampfkarren That worked, thanks.
