### ISSUE TITLE
Order of SharedStrings section changes in each time a rbxmx is generated

### ISSUE THREAD

**Issue by eAi** [rojo-rbx/remodel#59]
I've noticed that the order of the SharedStrings part of the file changes at random each time the remodel script runs. This leads to spurious changes in the files, which messes up diffs and causes more conflicts than necessary in git. This doesn't appear to affect other sections of the file, which seem to be generated deterministically.

I can write my own script to post-process these files and sort these shared strings by the md5, which should keep them consistent - but I think this would be a useful step to do anyway.

**Comment by LPGhatguy** [comment]
This has actually been fixed on the master branch for awhile as part of the upgrade to rbx-dom v2. I just started kicking off a Remodel 0.9.0 release which will have this fix, among other things!
