### ISSUE TITLE
remodel.writePlaceFile and remodel.writeModelFile do not write Part0 and Part1 properties

### ISSUE THREAD

**Issue by fredgig** [rojo-rbx/remodel#64]
When reading a `.rbxmx` or `.rbxlx` (xml) file and writing it as a `.rbxm` or `.rbxl` (binary) file, any `WeldConstraint` inside the `.rbxmx` or `.rbxlx` file will lose their `Part0` and `Part1` property values.

This is not an issue with other instance types containing `Part0` and `Part1` properties like `NoCollisionConstraint`, but I have not tested many others.

I noticed that exporting xml files from Roblox Studio will use `Part0Internal` and `Part1Internal` as property names for WeldConstraint's, so it might be related to this issue.

Let me know if you need any more detail.

**Comment by fredgig** [comment]
This issue now makes Remodel partly obsolete for us. It is no longer possible for us to publish our games with remodel.writeExistingPlaceAsset because WeldConstraint's are messed up in the process.

**Comment by badcc** [comment]
This is potentially same issue as https://github.com/rojo-rbx/rojo/issues/458, I just encountered on =0.9.1
