### ISSUE TITLE
Add remodel.removeFile(path: string) and remodel.removeFolder(path: string)

### ISSUE THREAD

**Issue by fredgig** [rojo-rbx/remodel#65]
I think the addition of `remodel.removeFile(path: string)` and `remodel.removeFolder(path: string)` would be great for managing workflows.

In my case, I currently have a remodel command that reads individual models within a place file and exports them as individual .rbxmx files to the file system. However, when I remove (:Destroy()) a model within the place, remodel is unable to also remove the corresponding .rbxmx file.

These two new functionalities could be implemented with [`fs::remove_file(path)`](https://doc.rust-lang.org/std/fs/fn.remove_file.html) and [`fs::remove_dir_all(path)`](https://doc.rust-lang.org/std/fs/fn.remove_dir_all.html) internally.

If you'd like me to, I can open a pull request.

**Comment by MrTaco9001** [comment]
You can use os.execute("rm -r {path}"). I do agree that this should be added, since it is easily implementable and keeps everything contained within Remodel

**Comment by Qualadore** [comment]
Right now on Windows I use `os.execute("rd /s /q \"" .. directory .. "\"")`, which prevents portability. This would be a great change.

**Comment by MrTaco9001** [comment]
`rm -r` works on Mac and PC

**Comment by Qualadore** [comment]
> `rm -r` works on Mac and PC

Not through cmd.

**Comment by MrTaco9001** [comment]
This is the exact function that I use. It works on PC and Mac, I develop on both. I have a VSCode task running that detects when the rbxlx file has been changed and runs remodel. It autocorrects the entire file system and syncs with what I have in studio. I'm not arguing that this function wouldn't be useful, but there are other ways. Everything is fully portable with GitHub and VSCode.
```lua
local function del(path)
	os.execute(string.format("rm -r %s", path))
	print(string.format("DELETED: [%s]", path))
end
```

**Comment by Qualadore** [comment]
I'm not sure what your environment is like, but that would error in a default Windows one. I know I could get around this, my point is just to highlight that this change would be useful.

**Comment by MrTaco9001** [comment]
I agree it would be very useful and cleaner

**Comment by MrTaco9001** [comment]
I stand corrected! I just tested on Windows and sure enough `rm` does not work
