### ISSUE TITLE
Add method to write single instance without its children

### ISSUE THREAD

**Issue by MrTaco9001** [rojo-rbx/remodel#66]
I would like to write individual instances without writing their children so that I can have remove any merge conflicts that may arise. I know you can do this by closing the instance then deleting all the children then blah blah blah, but it would be nice if it was a standalone method.

**Comment by MrTaco9001** [comment]
after some thought there would be no way to implement this in the way I had originally thought

**Comment by LPGhatguy** [comment]
This would actually be a useful API I think. I'm not sure how to do it well, but I'd love to do this in rbx-dom and then support it somehow in Remodel.
