### ISSUE TITLE
Support for aarch64/arm64 systems

### ISSUE THREAD

**Issue by RealCalumPlays** [rojo-rbx/remodel#72]

**Comment by RealCalumPlays** [comment]
Please add the enhancement tag.

**Comment by RealCalumPlays** [comment]
UPDATE: This isnt a highly in-demand thing but it would be nice so it can run on some oracle cloud machines

**Comment by LPGhatguy** [comment]
The next release of Remodel, 0.10.0, will have AArch64 binaries.
