### ISSUE TITLE
[ERROR] The system cannot find the file specified. (os error 2)

### ISSUE THREAD

**Issue by FSXplay** [rojo-rbx/remodel#77]
The path of the .lua file is correct, but why do I get this error?
<img width="530" alt="image" src="https://user-images.githubusercontent.com/95726321/173050533-3b6fdff9-c00a-485b-add5-491421487b0e.png">

**Comment by LPGhatguy** [comment]
This just looks like a bad error message on Remodel's part. When you have a space in your file path, you need to put the path in quotes. Your path has a space, and thus needs to be quoted.
