### ISSUE TITLE
Remodel no longer able to pull Roblox auth from studio

### ISSUE THREAD

**Issue by fewkz** [rojo-rbx/remodel#86]
I logged into Roblox Studio on a new computer and when trying to run remodel it says it wasn't able to find authentication cookie from studio. It seems like a recent version of studio changed how authentication is stored in studio.

**Comment by LPGhatguy** [comment]
Thanks for filing an issue. Yeah, I think Roblox Studio changed from storing the cookie as plaintext in the registry to using Windows' built-in credential store.

**Comment by SnowdustDev** [comment]
Here's a thread with some useful info regarding this
https://twitter.com/Anaminus/status/1560018529939820551

**Comment by filiptibell** [comment]
We could use https://github.com/blake-mealey/mantle/tree/main/rbx_cookie as our auth cookie implementation which solves this and also gives us support for macOS for free. It has worked well for our internal tooling so far and seems to also work well in Mantle.

If taking up `rbx_cookie` as a dependency is fine I can make a PR for it
