### ISSUE TITLE
In what scenario would I use Remodel?

### ISSUE THREAD

**Issue by Jamtoad** [rojo-rbx/remodel#97]
I just have a quick question, in what scenario would I use Remodel? I am trying to understand the "Why?" and I am having a hard time. This looks like an amazing repo, and I would love to use it, but I am confused as to where I would need it?

Thank you and have a good one!

**Comment by eAi** [comment]
It’s a good question and one that isn’t really answered well, but a common answer is that it’s useful as a tool to pair with Rojo.

Our workflow (which I believe is quite standard) is to use remodel to extract rbxmx from an rbxlx/rbxl files that we then check into git. Then we use Rojo to do the reverse and assemble the rbxmx files and lua files into an rbxlx/rbxl file.

This does involve writing a remodel lua script that matches up with the Rojo file.

Our workflow is to have two batch files that we run, one to 'extract' the models from the rbxlx file with remodel, and another to use rojo to build the rbxlx file. It's not directly relevant here, but our workflow is also that we only serve code with Rojo as we've found that serving models isn't very reliable as certain properties cannot be synced with Rojo and this isn't really required if you're happy to quit Roblox Studio each time you build the rbxlx file (which is probably each time you pull from git).

**Comment by Jamtoad** [comment]
So you primarily use it to get the models into a form where they can be pushed to GitHub?

**Comment by eAi** [comment]
Yes. It can also modify the files as part of that process, or save out rbxlx files.

**Comment by Jamtoad** [comment]
> Yes. It can also modify the files as part of that process, or save out rbxlx files.

Ohhhh okay, I got it now. Thank you!
