### ISSUE TITLE
Remodel run with correct Path causes a os error 3 for some reason

### ISSUE THREAD

**Issue by hamburg21035** [rojo-rbx/remodel#99]
I tried to run a script to build a file, but every time I try to run it, it gives me an error. I tried multiple files, reinstalling Remodel and changing Paths. I am right now in need of help.[](url)
![Screenshot 2023-03-18 180301](https://user-images.githubusercontent.com/79205395/226121975-2ba4c8f0-08d6-4aee-ad1d-0d2a33368b3c.png)

**Comment by LPGhatguy** [comment]
This is an error occurring inside your script. You appear to be calling the `readDir` function on a directory that does not exist. Remodel is finding your script and running it okay.

**Comment by hamburg21035** [comment]
The issue is, that the directory actually is existing. Maybe I just have configured the file wrong. I am right now not really sure. 
![Screenshot 2023-03-21 201600](https://user-images.githubusercontent.com/79205395/226717646-bca964bd-a3dc-403a-a3d9-d870dfb7fa07.png)
![Screenshot 2023-03-21 201858](https://user-images.githubusercontent.com/79205395/226717906-d2708526-cd15-45a6-8dc3-d35c70e11fa2.png)

**Comment by LPGhatguy** [comment]
The paths provided to `readDir` are relative to your working directory, not the directory that the script is in. `readDir("songs")` when run from your user directory will look for that directory in your user directory.

This is not unique to Remodel; I recommend looking into how programs inherit working directories and how it impacts the code that you write.
